# Generated by Django 4.1.5 on 2023-02-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_day', models.IntegerField(verbose_name='ini_day')),
                ('day', models.IntegerField(verbose_name='day')),
                ('time', models.CharField(max_length=100, verbose_name='研学时间')),
                ('reason', models.TextField(verbose_name='原因')),
                ('user_id', models.IntegerField(max_length=11, verbose_name='姓名')),
            ],
        ),
    ]
