# Generated by Django 4.1.5 on 2023-02-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_info_integrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='user_id',
            field=models.IntegerField(verbose_name='姓名'),
        ),
    ]
