# Generated by Django 4.1.5 on 2023-02-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_info_integrate', '0002_alter_leaveinfo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='day',
            field=models.DateField(verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='ini_day',
            field=models.DateField(verbose_name='ini_day'),
        ),
    ]
