# Generated by Django 4.1.5 on 2023-02-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_info_integrate', '0003_alter_leaveinfo_day_alter_leaveinfo_ini_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='time',
            field=models.CharField(max_length=200, verbose_name='研学时间'),
        ),
    ]
