# Generated by Django 4.1.5 on 2023-02-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_info_integrate', '0004_alter_leaveinfo_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('user_name', models.CharField(max_length=200, verbose_name='姓名')),
                ('phase_num', models.CharField(max_length=200, verbose_name='期数')),
                ('direction', models.CharField(max_length=200, verbose_name='方向')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='time',
            field=models.CharField(max_length=100, verbose_name='研学时间'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='user_id',
            field=models.IntegerField(verbose_name='学号'),
        ),
    ]
