# Generated by Django 4.1.4 on 2023-02-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('user_name', models.CharField(max_length=200, verbose_name='姓名')),
                ('phase_num', models.CharField(max_length=200, verbose_name='期数')),
                ('direction', models.CharField(max_length=200, verbose_name='方向')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
        ),
    ]
