# Generated by Django 4.1.4 on 2023-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
            ],
        ),
    ]
